### ISSUE TITLE
No module named 'cpu'

### ISSUE THREAD

**Issue by Ialys** [bexxmodd/vizex#17]
Hello,

I tried to run vizex from both repositories and after building it myself however in both case I got this error :
```
> vizex
Traceback (most recent call last):
  File "/usr/local/bin/vizex", line 11, in <module>
    load_entry_point('vizex==1.5.1', 'console_scripts', 'vizex')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/vizex-1.5.1-py3.8.egg/cli.py", line 8, in <module>
ModuleNotFoundError: No module named 'cpu'
```
OS is Ubuntu 20.04

```
> sudo python3 setup.py install
running install
running bdist_egg
running egg_info
writing src/vizex.egg-info/PKG-INFO
writing dependency_links to src/vizex.egg-info/dependency_links.txt
writing entry points to src/vizex.egg-info/entry_points.txt
writing requirements to src/vizex.egg-info/requires.txt
writing top-level names to src/vizex.egg-info/top_level.txt
reading manifest file 'src/vizex.egg-info/SOURCES.txt'
writing manifest file 'src/vizex.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
copying build/lib/cli.py -> build/bdist.linux-x86_64/egg
copying build/lib/tools.py -> build/bdist.linux-x86_64/egg
copying build/lib/disks.py -> build/bdist.linux-x86_64/egg
copying build/lib/charts.py -> build/bdist.linux-x86_64/egg
copying build/lib/battery.py -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/cli.py to cli.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/tools.py to tools.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/disks.py to disks.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/charts.py to charts.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/battery.py to battery.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying src/vizex.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/vizex.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/vizex.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/vizex.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/vizex.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/vizex.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/vizex-1.5.1-py3.8.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing vizex-1.5.1-py3.8.egg
Removing /usr/local/lib/python3.8/dist-packages/vizex-1.5.1-py3.8.egg
Copying vizex-1.5.1-py3.8.egg to /usr/local/lib/python3.8/dist-packages
vizex 1.5.1 is already the active version in easy-install.pth
Installing vizex script to /usr/local/bin

Installed /usr/local/lib/python3.8/dist-packages/vizex-1.5.1-py3.8.egg
Processing dependencies for vizex==1.5.1
Searching for toml==0.10.2
Best match: toml 0.10.2
Adding toml 0.10.2 to easy-install.pth file

Using /usr/local/lib/python3.8/dist-packages
Searching for six==1.15.0
Best match: six 1.15.0
Adding six 1.15.0 to easy-install.pth file

Using /usr/local/lib/python3.8/dist-packages
Searching for pytz==2020.5
Best match: pytz 2020.5
Adding pytz 2020.5 to easy-install.pth file

Using /usr/local/lib/python3.8/dist-packages
Searching for python-dateutil==2.8.1
Best match: python-dateutil 2.8.1
Adding python-dateutil 2.8.1 to easy-install.pth file

Using /usr/local/lib/python3.8/dist-packages
Searching for pytest==6.2.1
Best match: pytest 6.2.1
Adding pytest 6.2.1 to easy-install.pth file
Installing py.test script to /usr/local/bin
Installing pytest script to /usr/local/bin

Using /usr/local/lib/python3.8/dist-packages
Searching for pyparsing==2.4.7
Best match: pyparsing 2.4.7
Adding pyparsing 2.4.7 to easy-install.pth file

Using /usr/local/lib/python3.8/dist-packages
Searching for py==1.10.0
Best match: py 1.10.0
Adding py 1.10.0 to easy-install.pth file

Using /usr/local/lib/python3.8/dist-packages
Searching for psutil==5.8.0
Best match: psutil 5.8.0
Adding psutil 5.8.0 to easy-install.pth file

Using /usr/local/lib/python3.8/dist-packages
Searching for pluggy==0.13.1
Best match: pluggy 0.13.1
Adding pluggy 0.13.1 to easy-install.pth file

Using /usr/local/lib/python3.8/dist-packages
Searching for pandas==1.2.1
Best match: pandas 1.2.1
Adding pandas 1.2.1 to easy-install.pth file

Using /usr/local/lib/python3.8/dist-packages
Searching for packaging==20.8
Best match: packaging 20.8
Adding packaging 20.8 to easy-install.pth file

Using /usr/local/lib/python3.8/dist-packages
Searching for numpy==1.19.5
Best match: numpy 1.19.5
Adding numpy 1.19.5 to easy-install.pth file
Installing f2py script to /usr/local/bin
Installing f2py3 script to /usr/local/bin
Installing f2py3.8 script to /usr/local/bin

Using /usr/local/lib/python3.8/dist-packages
Searching for iniconfig==1.1.1
Best match: iniconfig 1.1.1
Adding iniconfig 1.1.1 to easy-install.pth file

Using /usr/local/lib/python3.8/dist-packages
Searching for colored==1.4.2
Best match: colored 1.4.2
Adding colored 1.4.2 to easy-install.pth file

Using /usr/local/lib/python3.8/dist-packages
Searching for click==7.1.2
Best match: click 7.1.2
Adding click 7.1.2 to easy-install.pth file

Using /usr/local/lib/python3.8/dist-packages
Searching for attrs==20.3.0
Best match: attrs 20.3.0
Adding attrs 20.3.0 to easy-install.pth file

Using /usr/local/lib/python3.8/dist-packages
Finished processing dependencies for vizex==1.5.1
```

cpu.py is missing in :
```
copying build/lib/cli.py -> build/bdist.linux-x86_64/egg
copying build/lib/tools.py -> build/bdist.linux-x86_64/egg
copying build/lib/disks.py -> build/bdist.linux-x86_64/egg
copying build/lib/charts.py -> build/bdist.linux-x86_64/egg
copying build/lib/battery.py -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/cli.py to cli.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/tools.py to tools.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/disks.py to disks.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/charts.py to charts.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/battery.py to battery.cpython-38.pyc
```

Thank you for the help.

**Comment by bexxmodd** [comment]
Yeah, this one was added but forgot to push the changed version. Thanks for bringing it to the attention

**Comment by perigoso** [comment]
Sorry, but it seems to not be corrected, as it is I am unable to build the package
